exclude_files = {
    ".luacheckrc",
    "Libs/",
}

-- https://luacheck.readthedocs.io/en/stable/warnings.html

ignore = {
--  "211",      -- Unused local variable
    "212/self", -- Unused argument
    "212/...",  -- Unused argument
--  "213",      -- Unused loop variable
    "432/self", -- Shadowing a local variable
--  "542",      -- empty if branch
    "631",      -- line too long
}

globals = {
    "LiteBagDB",
    "LiteBagBagButtonMixin",
    "LiteBagDragButtonMixin",
    "LiteBagSnapAnchor",
}

read_globals = {
    "AnchorUtil",
    "BACKPACK_TOOLTIP",
    "BagBarExpandToggle",
    "BagItemAutoSortButton",
    "BagItemSearchBox",
    "BagsBar",
    "BankFrame",
    "BankPanel",
    "BankPanelTabMixin",
    "BRIGHTBLUE_FONT_COLOR",
    "C_Container",
    "C_EquipmentSet",
    "C_Item",
    "C_TooltipInfo",
    "C_XMLUtil",
    "COMBINED_BAG_TITLE",
    "CONTAINER_OFFSET_Y",
    "ContainerFrame1",
    "ContainerFrame2",
    "ContainerFrame3",
    "ContainerFrame4",
    "ContainerFrame5",
    "ContainerFrame6",
    "ContainerFrameCombinedBags",
    "ContainerFrameMixin",
    "ContainerFrameSettingsManager",
    "ContinuableContainer",
    "CreateFrame",
    "CursorHasItem",
    "DEFAULT",
    "EditModeUtil",
    "Enum",
    "EQUIP_CONTAINER",
    "EventRegistry",
    "GameFontNormalSmall",
    "GameTooltip_SetTitle",
    "GameTooltip",
    "GENERAL",
    "GetExpansionName",
    "GetInventoryItemTexture",
    "GetInventorySlotInfo",
    "GetLocale",
    "GREEN_FONT_COLOR",
    "GridLayoutMixin",
    "HIGHLIGHT_FONT_COLOR",
    "hooksecurefunc",
    "InCombatLockdown",
    "IsAccountSecured",
    "ITEM_ACCOUNTBOUND_UNTIL_EQUIP",
    "ITEM_ACCOUNTBOUND",
    "ITEM_BIND_ON_EQUIP",
    "ITEM_BIND_ON_PICKUP",
    "ITEM_BIND_ON_USE",
    "ITEM_BIND_TO_ACCOUNT",
    "ITEM_BIND_TO_BNETACCOUNT",
    "ITEM_BNETACCOUNTBOUND",
    "ITEM_INVENTORY_BAG_BIT_OFFSET",
    "ITEM_INVENTORY_BANK_BAG_OFFSET",
    "ITEM_INVENTORY_LOCATION_BAGS",
    "ITEM_INVENTORY_LOCATION_BANK",
    "ITEM_INVENTORY_LOCATION_PLAYER",
    "ITEM_QUALITY_COLORS",
    "ITEM_SOULBOUND",
    "Item",
    "LibStub",
    "LOCK_FRAME",
    "MainMenuBarBagManager",
    "MenuUtil",
    "MicroButtonAndBagsBar",
    "NEVER",
    "PickupBagFromSlot",
    "PutItemInBackpack",
    "PutItemInBag",
    "RED_FONT_COLOR",
    "ResetCursor",
    "SetItemButtonTexture",
    "Settings",
    "SETTINGS",
    "tContains",
    "tInvert",
    "TOOLTIP_BATTLE_PET",
    "TooltipUtil",
    "UIParent",
}
